import Head from "next/head";
import styled from "@emotion/styled";
import { ReactNode } from "react";

interface LayoutProps {
  title: string;
  children: ReactNode;
}

const Container = styled.div`
  padding: 0 2rem;
`;

const Layout = ({ title, children }: LayoutProps) => {
  return (
    <Container>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {children}
    </Container>
  );
};

export default Layout;
